{% set name = "vistrans" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python>=3.6
    - pytorch>=1.4
    - torchvision >=0.5
  run:
    - python>=3.6
    - pytorch>=1.4
    - torchvision >=0.5

about:
  home: https://github.com/nachiket273/VisTrans
  license: MIT
  license_family: MIT
  summary: Implementations of transformers based models for different vision tasks
