name: Publish Conda Package

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: publish-to-conda
      uses: nachiket273/VisTrans@main
      with:
        subdir: '.conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'win osx linux'
